# AWS S3 bucket for static website hosting - CloudFormation Template

# TODO:
# 1. Add template for CodePipeline for deployment of the static website from github to s3 bucket

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'S3 bucket for static website hosting.'

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: maximdomentii.com
#      VersioningConfiguration:
#        Status: Enabled
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Delete

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
            Principal: '*'

Outputs:
  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of the S3 bucket.

  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: Website URL of the S3 bucket hosting the contact form.